# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248c482dff63440371e5f2180cf2e925617b0fc02b190aa05b84f05bac5d9160cc72529bd352c1b657e82c21885284a8f6dfed1ffe339ac7a6a639f0464325f8

test:
  secret_key_base: d81e6c15ec233d66ee4d737c49ac503523e74f54f378105af490cfac5c7d4f8ea8e678f3734a901af26feaf2404b6f0766c708f5504ea52bc5a3003598f9f8fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
